export const theme = {
    caribbeanGreen: '#02DC83',
    greenMedium: '#1FC07F',
    shamRockGreen: '#00A15F',
    bottleGreen: '#396347',
    darkestGreen: '#28372d',
    blueLight: '#69ACFA',
    blueMedium: '#057AFF',
    blueDark: '#006DE8',
    golden: '#FFC700',
    greyLight2: '#E8ECF2',
    darkGray: '#c4c4c4',
    text: '#333333',
    clearGray: '#fafafa',
    greyLight5: '#EDEDED',
    timberwolf: '#D8D8D8',
    greyLight7: '#DDE3E8',
    taupeGray: "#929292",
    red: '#D0021B',
    coolBlack: '#002954',
    white: '#ffffff',
    fontWeights: {
        bold: 'bold',
        medium: '500',
        light: 'normal'
    },
    fontsSizes: {
        'XXXL': '48px',
        'XXL': '36px',
        'XL': '28px',
        'L': '24px',
        'M': '20px',
        'S': '18px',
        'XS': '16px',
        'XXS': '14px',
        'XXXS': '12px',
    },
    lineHeights: {
        'XXXL': '64px',
        'XXL': '56px',
        'XL': '48px',
        'L': '48px',
        'M': '40px',
        'S': '36px',
        'XS': '24px',
        'XXS': '24px',
        'XXXS': '20 px',
    },
    spacing: {
        0: '0px',
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
        20: '80px',
        24: '96px',
        32: '128px',
        40: '160px',
        48: '192px',
        56: '224px',
        64: '256px'
    },

    size: {
        mobileS: '320px',
        mobileM: '375px',
        mobileL: '425px',
        tablet: '768px',
        laptop: '1024px',
        laptopL: '1440px',
        desktop: '2560px'
    }
};

export const device = {
    mobileS: `(min-width: ${theme.size.mobileS})`,
    mobileM: `(min-width: ${theme.size.mobileM})`,
    mobileL: `(min-width: ${theme.size.mobileL})`,
    tablet: `(min-width: ${theme.size.tablet})`,
    laptop: `(min-width: ${theme.size.laptop})`,
    laptopL: `(min-width: ${theme.size.laptopL})`,
    desktop: `(min-width: ${theme.size.desktop})`,
    desktopL: `(min-width: ${theme.size.desktop})`
};