const IS_LOADING = "IS_LOADING";
const CITIES_FETCH_SUCCCESS = "CITIES_FETCH_SUCCCESS";
const CITIES_FETCH_FAIL = "CITIES_FETCH_FAIL";

module.exports = {
    IS_LOADING,
    CITIES_FETCH_FAIL,
    CITIES_FETCH_SUCCCESS
} 