const IS_LOADING = "IS_LOADING";
const CITIES_FETCH_SUCCCESS = "CITIES_FETCH_SUCCCESS";
const CITIES_FAIL = "CITIES_FAIL";
const CITIES_SET_FILTER = "CITIES_SET_FILTER";
const CITIES_CLEAR = "CITIES_CLEAR";
const CITIES_SELECT_ADD = "CITIES_SELECT_ADD";
const CITIES_SELECT_REMOVE = "CITIES_SELECT_REMOVE";

module.exports = {
    CITIES_CLEAR, 
    CITIES_SELECT_ADD,
    CITIES_SELECT_REMOVE,
    IS_LOADING,
    CITIES_FAIL,
    CITIES_FETCH_SUCCCESS,
    CITIES_SET_FILTER
} 