const IS_LOADING = "IS_LOADING";
const CITIES_FETCH_SUCCCESS = "CITIES_FETCH_SUCCCESS";
const CITIES_FETCH_FAIL = "CITIES_FETCH_FAIL";
const CITIES_SET_FILTER = "CITIES_SET_FILTER";

module.exports = {
    IS_LOADING,
    CITIES_FETCH_FAIL,
    CITIES_FETCH_SUCCCESS,
    CITIES_SET_FILTER
} 